export const columnVisibility = {
  concessionaire: [
    "gid",
    "id",
    "standpipe",
    "book",
    "sp_id",
    "account",
    "name",
    "status",
  ],
  standpipe: [
    "gid",
    "elevation",
    "standpipe",
    "remarks",
    "db_book",
    "date_inspected",
    "status",
    "substandard_category",
    "service_line_size",
  ],
  pipeline: [
    "gid",
    "location",
    "size",
    " type",
    " pipe",
    "stddepth_m",
    "length_m",
    "length2_m",
    "project_mo",
    "date_insta",
    "remarks",
  ],
  "distribution valves": [
    "name",
    "location",
    "status",
    "remarks",
    "date_installed",
    "valve_size_inches",
    "dv_id",
    "valve_id",
  ],
  "hydrants and bovs": [
    "description",
    "size",
    "fh_bov",
    "remarks",
    "area",
    "fid",
  ],
  "pumping stations": ["name", "area", "date"],
  "2024_land_rights": ["loc_desc", "location", "date"],
  service_line: [
    "line_location",
    "size_in",
    "pipe",
    "remarks",
    "monitored_by",
    "date_installed",
  ],
  water_schedule: [
    "Name",
    "description",
    "Water Source",
    "Time",
    "Updated By",
    "Date Updated",
    "Remarks",
  ],
  arvs: [
    "name",
    "size",
    "settings",
    "date_set",
    "remarks",
    "date_updated",
  ],
};
